"""empty message

Revision ID: 96ef8f80d70c
Revises: 412b1aea1d70
Create Date: 2022-03-11 11:37:58.422561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96ef8f80d70c'
down_revision = '412b1aea1d70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('devices_serial_number_key', 'devices', type_='unique')
    op.drop_index('model_index', table_name='devices')
    op.alter_column('user_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'user_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'user_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('user_type_index', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_type_index', 'users', ['user_type'], unique=False)
    op.alter_column('users', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'user_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('user_accounts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('model_index', 'devices', ['model'], unique=False)
    op.create_unique_constraint('devices_serial_number_key', 'devices', ['serial_number'])
    op.alter_column('devices', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
